### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by stxacp** [lbcb-sci/racon#10]
Hi, 

I'm installing racon, and when I get to the make command I get these errors at the end:

ld: library not found for -ledlib_static
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/racon] Error 1
make[1]: *** [CMakeFiles/racon.dir/all] Error 2
make: *** [all] Error 2

I'm not sure how to solve this, any ideas?

Cheers

**Comment by rvaser** [comment]
Hello,
can you paste the commands you used to clone and build racon?

Best regards,
Robert

**Comment by stxacp** [comment]
So, I followed the commands given in the installation instructions on the racon page. Weirdly though, when git cloning I had to install bioparser and all the other packages as they didn't down load when git cloning. 
Could this be why?

git clone --recursive https://github.com/lbcb-sci/racon.git racon
cd racon
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make

**Comment by rvaser** [comment]
Could be if you did not add `--recursive` in the command. This way only the main project is cloned without submodules. May I assume that you closing the issue means that you were able to compile it this time?

**Comment by stxacp** [comment]
Hey, yes, turns out I was being an idiot, completely missed that. Sorry for wasting your time!

**Comment by rvaser** [comment]
No problem, happens!:)
