### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ilyavs** [lbcb-sci/racon#11]
Hi,
I installed racon 1.4.10 using bioconda. Although I intend on using it on a cluster, I first tested it on the machine on which I ran the conda install command. Even though I ran it on the same machine I used for installing it, I still got the "Illegal instruction (core dumped)" error.
The compiler on the machine is: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Will I have to compile racon from source on each of the cluster machines once I get it to work on the current one?
I appreciate your help in getting racon to work on my system.
Thanks,
Ilya.

**Comment by rvaser** [comment]
Hi Ilya,
try compiling from source on one of your machines and see if that executable works on others. I am not sure what exactly is causing the error, which CPU do you have? Does it support SSE4.1?

Best regards,
Robert

**Comment by ilyavs** [comment]
Hi,
I didn't change anything in the installation and ran it on the cluster. I think it crashed a couple of times with a similar error. However, once I requested larger amounts of memory (50Gb), it crashed less often (with the same error, at different stages).
Could it be that the issue is related to available memory?
Thanks,
Ilya.

**Comment by ilyavs** [comment]
Another update, jobs that failed with 50Gb memory, completed successfully with 150Gb memory.
Best,
Ilya.

**Comment by rvaser** [comment]
The illegal instruction error is not tied to insufficient memory. Maybe you got a different node on the cluster that is compatible with the binary.

Best regards,
Robert

**Comment by ilyavs** [comment]
Maybe. Anyway, seems to work in my current workflow.
Thanks,
Ilya.
