### ISSUE TITLE
Issue with using Racon in pipeline-pinfish-analysis

### ISSUE THREAD

**Issue by charlottewright** [lbcb-sci/racon#14]
I am attempting to use Racon within the pipeline-pinfish-analysis Snakefile but the workflow fails at the point of polishing the transcripts. The sdtout file suggests that the issue is with Racon.

The full error message is:

polish_clusters: 16:17:30 Polishing cluster be37aa9e-8202-4afd-8c18-ebde5ef7c6fa of size 10
polish_clusters: 16:17:30 Failed running command: racon -t 20 -q -1  /tmp/pinfish_be37aa9e-8202-4afd-8c18-ebde5ef7c6fa_713003653/reads.fq /tmp/pinfish_be37aa9e-8202-4afd-8c18-ebde5ef7c6fa_713003653/alignments.s$
[Fri Dec  6 16:17:31 2019]
Error in rule polish_clusters:
    jobid: 7
    output: results/polished_transcripts.fas
    shell:

    /rds-d4/project/cj107/rds-cj107-jiggins-rds/projects/eratoCortexMapping/Nanopore/20191024_HW_Larva/pipeline-pinfish-analysis-fast-v4/pinfish/polish_clusters/polish_clusters -t 20 -a results/cluster_membersh$

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job polish_clusters since they might be corrupted:
results/polished_transcripts.fas

Other people in my group who have previously used racon within this pipeline are also having the same problem with racon, suggesting that this is a bug with racon rather than my installation. I am using racon v1.4.10

Has anything changed with racon to account for why we are now having issues?

Thank you in advance for your help.

**Comment by rvaser** [comment]
Hi Charlotte,
by the pipeline github page i meant https://github.com/nanoporetech/pipeline-pinfish-analysis. This racon repository is the same as isovic/racon but with newer updates.

Best regards,
Robert
