### ISSUE TITLE
N50 decrease issue 

### ISSUE THREAD

**Issue by Tdanis** [lbcb-sci/racon#15]
Hi all , I found an interesting result for me, after running Racon on some data. It seems tha after running Racon 3 rounds and more , the N50 decreased dramatically, some times below of the half.   
Did you have any suggestions of what it happens ? 

Thank you

**Comment by rvaser** [comment]
Hello,
not sure what is causing such drastic decrease in length. Would you maybe share your data so I can investigate?

Best regards,
Robert

**Comment by Tdanis** [comment]
Sory but I can not share my data yet. But this decrese every time I run Racon more than 3 rouns  or a software which incorporates Racon , again more than 3 rounds. If you have any suggestions inform me please , because is so weird to me .

**Comment by rvaser** [comment]
I think that polishing might have increased your total assembly length and the N50 value you had was invalidated and replaced by a smaller contig.

**Comment by Tdanis** [comment]
Thank you for your reply,

But how it can be this possible?  
After assessment, indeed polishing improves my draft assembly , with a small decrease after several rounds , but N50 decreases drammatically. Frankly speaking I didnt check it after 5 rounds or so on.

**Comment by rvaser** [comment]
Try inspecting the total length, number of contigs and L50 value.

**Comment by Tdanis** [comment]
Thank you again
