### ISSUE TITLE
is replacing read names with integers still recommended?

### ISSUE THREAD

**Issue by evanrrees** [lbcb-sci/racon#16]
In the old Racon repository, there's a [recommendation](https://github.com/isovic/racon/issues/94#issuecomment-431106812) that read names be replaced with integers to speed up PAF parsing. Is this still recommended?

Thanks for a great tool!

**Comment by rvaser** [comment]
If you have a large read set with long names, then yes.

Best regards,
Robert

**Comment by evanrrees** [comment]
Great, thanks Robert!
-Evan
