### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by gortey** [lbcb-sci/racon#18]
In file included from /mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/sisd_alignment_engine.hpp:14,
                 from /mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/alignment_engine.cpp:11:
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: expected nested-name-specifier before 'Alignment'
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: 'Alignment' has not been declared
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: expected ';' before '=' token
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: expected unqualified-id before '=' token
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/include/spoa/alignment_engine.hpp:50: error: 'Alignment' does not name a type
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/include/spoa/alignment_engine.hpp:53: error: 'Alignment' does not name a type
In file included from /mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/alignment_engine.cpp:11:
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/sisd_alignment_engine.hpp:30: error: expected ';' before 'override'
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/sisd_alignment_engine.hpp:32: error: 'Alignment' does not name a type
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/sisd_alignment_engine.hpp:47: error: 'Alignment' does not name a type
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/sisd_alignment_engine.hpp:50: error: 'Alignment' does not name a type
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/sisd_alignment_engine.hpp:53: error: 'Alignment' does not name a type
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/sisd_alignment_engine.hpp:60: error: expected ';' before 'noexcept'
In file included from /mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/alignment_engine.cpp:12:
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/simd_alignment_engine.hpp:30: error: expected ';' before 'override'
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/simd_alignment_engine.hpp:32: error: 'Alignment' does not name a type
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/simd_alignment_engine.hpp:48: error: expected constructor, destructor, or type conversion before 'linear'
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/simd_alignment_engine.hpp:52: error: expected constructor, destructor, or type conversion before 'affine'
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/simd_alignment_engine.hpp:56: error: expected constructor, destructor, or type conversion before 'convex'
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/simd_alignment_engine.hpp:65: error: expected initializer before 'noexcept'
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/alignment_engine.cpp: In function 'std::unique_ptr<spoa::AlignmentEngine, std::default_delete<spoa::AlignmentEngine> > spoa::createAlignmentEngine(spoa::AlignmentType, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t)':
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/alignment_engine.cpp:37: error: 'invalid_argument' is not a member of 'std'
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/alignment_engine.cpp:41: error: 'invalid_argument' is not a member of 'std'
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/alignment_engine.cpp:45: error: 'invalid_argument' is not a member of 'std'
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/alignment_engine.cpp:63: error: 'nullptr' was not declared in this scope
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/alignment_engine.cpp: At global scope:
/mnt/ilustre/users/sanger-dev/home/gaohao/bacgenome_v2/racon/vendor/spoa/src/alignment_engine.cpp:76: error: 'Alignment' does not name a type
make[2]: *** [vendor/spoa/CMakeFiles/spoa.dir/src/alignment_engine.cpp.o] Error 1
make[1]: *** [vendor/spoa/CMakeFiles/spoa.dir/all] Error 2
make: *** [all] Error 2

can you help me ?

**Comment by rvaser** [comment]
Hello,
you have a too old version of the GCC compiler. Please paste output of `make VERBOSE=1`.

Best regards,
Robert
