### ISSUE TITLE
Metagenome polishing

### ISSUE THREAD

**Issue by cmaggior** [lbcb-sci/racon#28]
Hello, I'm interested in polishing a canu assembly of a metagenome, is it possible to input multiple read files and overlap files? e.g. multiple fastq and .sam files?
Thanks!

**Comment by rvaser** [comment]
Hello,
unfortunately you cannot pass multiple files in one run. You will need to run Racon for each pair separately.

Best regards,
Robert

**Comment by cmaggior** [comment]
Okay, thank you!
