### ISSUE TITLE
Illegal instruction error

### ISSUE THREAD

**Issue by EdHarry** [lbcb-sci/racon#3]
Reopening previous issue here

https://github.com/isovic/racon/issues/119

Seems to happen on AMD cpus only, at least from my experience.

**Comment by rvaser** [comment]
Hi Ed,
we are using Intel SIMD instructions (packages SSE4.1 and above) which if are not supported on machines different from the machine you compiled the code on will cause the error you got. If you compile on a machine without support, the code will fall back to unvectorized algorithms which will be slower. If you have a cluster with mismatching CPUs, try picking nodes that are compatible with each other.
 
Best regards,
Robert

**Comment by EdHarry** [comment]
AMD cpus support sse instructions. I use a lot of intel compiled software that use sse running on amd hardware, minimap2 for example. I also compiled from source in compatibility mode (x86-64). I can’t say for certain but I would guess it’s not an sse instruction that’s causing the problem.
I’m going to disassemble the binary and find the problem myself when I get the chance.

**Comment by oneillkza** [comment]
I'm seeing this same error with a Bioconda-installed racon on an Intel I7-3770. 

It runs without error on a  Xeon E7-8867 v4 server, using the same installation/binaries.

**Comment by rvaser** [comment]
Weird as I7-3770 should support SSE4.1. Maybe your libstdc++ is outdated? You can always try and compile from source.

**Comment by oneillkza** [comment]
Yeah could be a CentOS outdated-libraries thing. It is a bit weird, since both my workstation (the I7) and the server (the Xeon) are running CentOS 7. It's possible my workstation is just a bit out of date, though. I'll put in a request to get it updated and see if that helps.

**Comment by EdHarry** [comment]
I think I've found the problem, the spoa module you use has a cmake build option "spoa_optimize_for_native" that defaults to ON, that I think is overriding the CPP flags to set "-march=native". Turn that option off to get cross compilation working.

**Comment by rvaser** [comment]
The Bioconda recipe for racon adds `-DCMAKE_CXX_FLAGS="-mno-avx2"` to the compiler list (see [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/racon/build.sh)), which is propagated to Spoa where only the SSE4.1 part of the code is compiled. Does `-march=native` add some other flags that are problematic?

**Comment by EdHarry** [comment]
I’m pretty sure native compilation will essentially lock you in to the specific CPU model you compiled on, or newer models in the same line. For the bioconda release at least, I would strongly suggest turning native off (the current bioconda release doesn’t work on any AMD hardware, for example).
Without doing any tests myself, I would guess that native compilation won’t give you any significant performance boost anyway, since the SIMD instructions are all hardcoded.

With regards to AVX2 on or off for the bioconda release. May I suggest something like the following: you compile two versions (called say, racon.avx2 and racon.noavx2 for example) and then have the main racon executable be a shell script that does a runtime hardware determination (using say, lscpu) and dispatches to the appropriate binary. Do you think that something like that would be feasible?

**Comment by rvaser** [comment]
I'll see what I can do to sort this out.

**Comment by kjoost** [comment]
Hi,

I have some issues with running racon. my codes in racon and minimap2 are: minimap2 -x map-ont /home/fronglesquad/ISB_AB-contigs.fasta /home/fronglesquad/snakemake_V2_ISB8A-12-12-19/filtered/nanofilt_out.fastq.gz > aln_ISB_V1.sam
racon --threads 10 /home/fronglesquad/snakemake_V2_ISB8A-12-12-19/filtered/nanofilt_out.fastq.gz /home/fronglesquad/aln_ISB_V1.sam.gz /home/fronglesquad/ISB_AB-contigs.fasta > output_racon
I get the following error message: Illegal instruction (core dumped).
I dont get what I am doing wrong could you maybe help me?

**Comment by MaestSi** [comment]
Hi, are there any news regarding a working conda installation? I am able to run racon when compiling from source, but conda installation gives core dump error.
Thanks,
Simone

**Comment by rvaser** [comment]
Unfortunately, not yet.

**Comment by rvaser** [comment]
@EdHarry and @MaestSi, can you please try version `v1.4.11` from bioconda? I have replaced `-march=native` with `-msse4.1` in Spoa and propagated that to Racon.

I am really sorry for the delay!
Best regards,
Robert

**Comment by EdHarry** [comment]
Sure, I can try on Monday

**Comment by MaestSi** [comment]
Hi, I just tried racon v1.4.11 from bioconda, but the issue persists. I tested it on the same machine where I previously tested spoa, but differently to spoa the issue is not solved for racon yet.

**Comment by rvaser** [comment]
Does `racon --version` give you 1.4.11? I do not see it yet on https://bioconda.github.io/recipes/racon/README.html.

**Comment by EdHarry** [comment]
I think -march=x86-64 might need to be specified in the build options

**Comment by MaestSi** [comment]
Yes, it looks like.
```
conda list | grep racon
racon                     1.4.11               he513fc3_0    bioconda
```

**Comment by rvaser** [comment]
Hmmm, no idea why :/

**Comment by EdHarry** [comment]
Yes, same issue on AMD hardware for me.

**Comment by rvaser** [comment]
@EdHarry, can you please try if `spoa` is working on your machine? It is in bioconda as well.

**Comment by EdHarry** [comment]
Yes, spoa 3.0.2 from bioconda works

**Comment by rvaser** [comment]
Hmm, maybe something else is the problem in racon executable. I'll try to find out.

**Comment by rvaser** [comment]
@MaestSi and @EdHarry, can you please try if racon `v1.4.12` from bioconda works now?

**Comment by MaestSi** [comment]
Hi @rvaser , conda installation for racon v1.4.12 is now working for me!
Thanks,
Simone

**Comment by EdHarry** [comment]
Confirmed, version 1.4.12 from bioconda works for me on both Intel and AMD hardware.

**Comment by rvaser** [comment]
Finally! I found `-march=native` flag in the thread_pool submodule which was there for no reason. Glad that it works now for everyone :)
