### ISSUE TITLE
error: unequal lengths in sequence and overlap file for sequence

### ISSUE THREAD

**Issue by cmaggior** [lbcb-sci/racon#32]
Hello,

I'm receiving the following error message when trying to use racon with paired-end reads and minimap2-generated sam files with a mixed Illumina/nanopore metagenome:

error: unequal lengths in sequence and overlap file for sequence K00271:557:HCJ2HBBXY:1:1101:6167:998

I've made sure my reads do not have the same identifier using the advice in this thread: https://github.com/isovic/racon/issues/68. I've also tried running racon with just the forward reads of the paired reads, and still receive the same error. Can anyone offer any advice on this?

Thanks!

**Comment by rvaser** [comment]
Hello,
can you please paste the tool/command you used to get the overlap file? The command for Racon also, please.

Best regards,
Robert

**Comment by cmaggior** [comment]
Sure thing. For the overlap file, it's:

minimap2 -ax sr hybridcontigs_500.fasta R1_paired.fastq R2_paired.fastq > S1.sam

For racon, it's:

./racon R1_paired.fastq S1.sam hybrid_contigs500.fasta

I've also tried with both paired end reads and checked that the names are different with:

./racon S1.fastq S1.sam hybrid_contigs500.fasta

**Comment by rvaser** [comment]
Hmm, what is the difference between S1.fastq and R1_paired.fastq? Can you please run the commands bellow?
```bash
head -n 1 R1_paired.fastq
head -n 1 R2_paired.fastq
head -n 1 S1.fastq
grep -v "^@" S1.sam | head -n 1
```

**Comment by cmaggior** [comment]
Sure thing: R1_paired.fastq head is: @K00271:557:HCJ2HBBXY:1:1101:5680:998 1:N:0:NGTACTAG+NTAGCCTT

R2_paired.fastq head is: @K00271:557:HCJ2HBBXY:1:1101:5680:998 2:N:0:NGTACTAG+NTAGCCTT

S1.fastq head is: @K00271:557:HCJ2HBBXY:1:1101:5680:998 1:N:0:NGTACTAG+NTAGCCTT

S1.sam head is: K00271:557:HCJ2HBBXY:1:1101:5680:998	89	NODE_22409_length_1929_cov_136.746531	777	20	99M	=	777	-99	AGCCTGTGAAACTATCTTTCACAGGCTTTCTCGATTTAATAGGTGAATTTACTCTACATCTTTATCGCTTTCCNTACCAAAAAGATCCCCTTTTTTAAA	JJJJJJFJJJAJJJJJJFF-JAAJAJJJFA-JJFJJJF<FF<7F<-JJJJJJFFFFFJJJJJJJFJJJJFFFJ#FJJJJJJJJF<FFJJJJJJJJFFAA	NM:i:2	ms:i:185	AS:i:185	nn:i:1	tp:A:P	cm:i:3	s1:i:41	s2:i:0

Is part of the problem that the R1_paired.fastq and R2_paired.fastq heads match? I will rerun the script from https://github.com/isovic/racon/issues/68. But shouldn't it still be okay with running just R1_paired.fastq as the sequences used for correction?

Thanks!

**Comment by rvaser** [comment]
You have to join the sequence files first, run minimap2 with the combined file and then run Racon. The latest Racon version has the necessary script [here](https://github.com/lbcb-sci/racon/blob/master/scripts/racon_preprocess.py).

**Comment by cmaggior** [comment]
It worked, thank you so much!
