### ISSUE TITLE
Problem while installing racon on arm platform 

### ISSUE THREAD

**Issue by X-WJ** [lbcb-sci/racon#37]
I try to intasll racon on arm platform but here are some errors :
make VERBOSE=1 
/usr/local/src/cmake-3.6.2/bin/cmake -H/project/software/racon/racon-v1.4.13 -B/project/software/racon/racon-v1.4.13/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/src/cmake-3.6.2/bin/cmake -E cmake_progress_start /project/software/racon/racon-v1.4.13/build/CMakeFiles /project/software/racon/racon-v1.4.13/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/project/software/racon/racon-v1.4.13/build'
make -f vendor/edlib/CMakeFiles/edlib_static.dir/build.make vendor/edlib/CMakeFiles/edlib_static.dir/depend
make[2]: Entering directory `/project/software/racon/racon-v1.4.13/build'
cd /project/software/racon/racon-v1.4.13/build && /usr/local/src/cmake-3.6.2/bin/cmake -E cmake_depends "Unix Makefiles" /project/software/racon/racon-v1.4.13 /project/software/racon/racon-v1.4.13/vendor/edlib /project/software/racon/racon-v1.4.13/build /project/software/racon/racon-v1.4.13/build/vendor/edlib /project/software/racon/racon-v1.4.13/build/vendor/edlib/CMakeFiles/edlib_static.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/project/software/racon/racon-v1.4.13/build'
make -f vendor/edlib/CMakeFiles/edlib_static.dir/build.make vendor/edlib/CMakeFiles/edlib_static.dir/build
make[2]: Entering directory `/project/software/racon/racon-v1.4.13/build'
make[2]: Nothing to be done for `vendor/edlib/CMakeFiles/edlib_static.dir/build'.
make[2]: Leaving directory `/project/software/racon/racon-v1.4.13/build'
[  6%] Built target edlib_static
make -f vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/build.make vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/depend
make[2]: Entering directory `/project/software/racon/racon-v1.4.13/build'
cd /project/software/racon/racon-v1.4.13/build && /usr/local/src/cmake-3.6.2/bin/cmake -E cmake_depends "Unix Makefiles" /project/software/racon/racon-v1.4.13 /project/software/racon/racon-v1.4.13/vendor/bioparser/vendor/zlib /project/software/racon/racon-v1.4.13/build /project/software/racon/racon-v1.4.13/build/vendor/bioparser/vendor/zlib /project/software/racon/racon-v1.4.13/build/vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/project/software/racon/racon-v1.4.13/build'
make -f vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/build.make vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/build
make[2]: Entering directory `/project/software/racon/racon-v1.4.13/build'
make[2]: Nothing to be done for `vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/build'.
make[2]: Leaving directory `/project/software/racon/racon-v1.4.13/build'
[ 56%] Built target zlibstatic
make -f vendor/spoa/CMakeFiles/spoa.dir/build.make vendor/spoa/CMakeFiles/spoa.dir/depend
make[2]: Entering directory `/project/software/racon/racon-v1.4.13/build'
cd /project/software/racon/racon-v1.4.13/build && /usr/local/src/cmake-3.6.2/bin/cmake -E cmake_depends "Unix Makefiles" /project/software/racon/racon-v1.4.13 /project/software/racon/racon-v1.4.13/vendor/spoa /project/software/racon/racon-v1.4.13/build /project/software/racon/racon-v1.4.13/build/vendor/spoa /project/software/racon/racon-v1.4.13/build/vendor/spoa/CMakeFiles/spoa.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/project/software/racon/racon-v1.4.13/build'
make -f vendor/spoa/CMakeFiles/spoa.dir/build.make vendor/spoa/CMakeFiles/spoa.dir/build
make[2]: Entering directory `/project/software/racon/racon-v1.4.13/build'
[ 59%] Building CXX object vendor/spoa/CMakeFiles/spoa.dir/src/alignment_engine.cpp.o
cd /project/software/racon/racon-v1.4.13/build/vendor/spoa && /usr/bin/c++    -I/project/software/racon/racon-v1.4.13/src -I/project/software/racon/racon-v1.4.13/vendor/spoa/include  -Wall -Wextra -pedantic -Wall -Wextra -pedantic -march=native -O3 -DNDEBUG   -std=c++11 -o CMakeFiles/spoa.dir/src/alignment_engine.cpp.o -c /project/software/racon/racon-v1.4.13/vendor/spoa/src/alignment_engine.cpp
/project/software/racon/racon-v1.4.13/vendor/spoa/src/alignment_engine.cpp:1:0: error: unknown value ‘native’ for -march

my gcc version and cmake info is 
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
cmake version 3.6.2

Best Regrads

**Comment by X-WJ** [comment]
I solved it by editing this file .
/project/software/racon/racon-v1.4.13/vendor/spoa/CMakeLists.txt 
if (spoa_optimize_for_portability)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=armv8-a")
elseif (spoa_optimize_for_native)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ~~-march=nativa~~ )    
endif()

also  edit this file 
copy sse2neon.h to thie dir of simd_alignment_engine.cpp where is 
edit simd_alignment_engine.cpp
 // #include <immintrin.h> // AVX2 and lower
   #include "sse2neon.h"   //new this line

**Comment by rvaser** [comment]
Hello,
I am aware that the current implementation is not compatible with ARM platforms (see https://github.com/isovic/racon/issues/151), but did not have the time yet to solve it.

Best regards,
Robert

**Comment by rvaser** [comment]
We have updated spoa inside racon to the latest version, which has various compilation parameters that can be used for different platforms (e.g. SIMDe).
