### ISSUE TITLE
report of the count of corrections

### ISSUE THREAD

**Issue by splaisan** [lbcb-sci/racon#41]
Hi
Is there a way to report the number of corrections done during a pass. Pilon does it and it is nice to evaluate the effect of successive rounds and decide to stop early enough. I probably missed it here.
thanks

**Comment by rvaser** [comment]
Hi Stephane,
there is no report on how many changes have been made. The only thing reported is the number of windows polished, which is written to sequence headers in form of `XC:f:<percenrage>`.

Best regards,
Robert

**Comment by splaisan** [comment]
Thanks Robert
