### ISSUE TITLE
Error compiling racon

### ISSUE THREAD

**Issue by asan-emirsaleh** [lbcb-sci/racon#46]
Hi!
I am working around two days trying to compile racon with GPU support enabled.
GCC = 9.3.0
cmake = 3.18.20200908-g1d74a64
make = 4.3
nvcc = 11.0
cuDNN = 8.0.2
nvidia driver = 450.51.06

CMakeCache.txt was manually edited with including `CMAKE_CXX_FLAGS:STRING=-DFMT_USE_USER_DEFINED_LITERALS=0` string
A compilation aborted with error:
`[ 81%] Linking CXX static library ../../lib/libcudaaligner.a Reaping winning child 0x55c2e3d8eaf0 PID 14870 Live child 0x55c2e3d8eaf0 (lib/libcudaaligner.a) PID 14872 Reaping winning child 0x55c2e3d8eaf0 PID 14872 Live child 0x55c2e3d8eaf0 (lib/libcudaaligner.a) PID 14874 Reaping winning child 0x55c2e3d8eaf0 PID 14874 Removing child 0x55c2e3d8eaf0 PID 14874 from chain. Considering target file 'GenomeWorks/cudaaligner/CMakeFiles/cudaaligner.dir/build'. File 'GenomeWorks/cudaaligner/CMakeFiles/cudaaligner.dir/build' does not exist. Considering target file 'lib/libcudaaligner.a'. File 'lib/libcudaaligner.a' was considered already. Finished prerequisites of target file 'GenomeWorks/cudaaligner/CMakeFiles/cudaaligner.dir/build'. Must remake target 'GenomeWorks/cudaaligner/CMakeFiles/cudaaligner.dir/build'. Successfully remade target file 'GenomeWorks/cudaaligner/CMakeFiles/cudaaligner.dir/build'. Reaping winning child 0x558a0914daf0 PID 14802 Live child 0x558a0914daf0 (GenomeWorks/cudaaligner/CMakeFiles/cudaaligner.dir/all) PID 14879 [ 81%] Built target cudaaligner Reaping winning child 0x558a0914daf0 PID 14879 Removing child 0x558a0914daf0 PID 14879 from chain. Reaping losing child 0x560a19aabcb0 PID 14245 make: *** [Makefile:171: all] Error 2 Removing child 0x560a19aabcb0 PID 14245 from chain.`

I maintain all prerequisites be OK and I have no idea how to configure cmake and make for compiling.
Thak you.

**Comment by rvaser** [comment]
Hi Asan,
hopefully @tijyojwad can assist you with your enquiry.

Best regards,
Robert

**Comment by tijyojwad** [comment]
Hi @asantat we merged a hot fix into GenomeWorks to address your issue - could you perhaps check the version of racon with that hotifx in https://github.com/lbcb-sci/racon/pull/47 to see if you get unblocked?

**Comment by asan-emirsaleh** [comment]
I verified the fix. Racon was successfully compiled with gcc-9 and CUDA 11.

The cmake arguments I used was
`
sudo cmake -DCMAKE_BUILD_TYPE=Release -Dracon_enable_cuda=ON -DCMAKE_CXX_FLAGS:STRING=-DFMT_USE_USER_DEFINED_LITERALS=0 -DCUDA_cupti_LIBRARY:FILEPATH=/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcupti.so -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 ..
`
Because a cupti library is an only one which is not detected by cmake and I usually add it manually to CmakeCache.txt or pass to the arguments.
So, both Racon and GenomeWorks+Racon are compiling with gcc7 and gcc9 without errors occured.
