### ISSUE TITLE
segmentaion fault

### ISSUE THREAD

**Issue by MichelMoser** [lbcb-sci/racon#5]
Hi, 

I run into segmentation fault when running racon with following parameters

```
 tools/racon/build/bin/racon -t 20 -m 8 -x -6 -g -8 -w 500 -u $FASTQ reads_2_assembly.sam.gz assembly.fasta > racon_polish.fa 
[racon::Polisher::initialize] loaded target sequences 2.781627 s
[racon::Polisher::initialize] loaded sequences 426.328405 s
Segmentation fault
```

There should be plenty of memory on the machine. 

```
                total        used        free      shared  buff/cache   available 
Mem:           3.0T        118G        2.8T        4.1G        9.6G        2.8T  

```

Using gzipped sam as input format and racon version v1.4.7
Any help would be appreciated. 

Thanks

**Comment by rvaser** [comment]
Hi Michel,
maybe there is a bug in the parser. How big is the SAM File? Could you maybe share it so I can investigate locally?

Best regards,
Robert

**Comment by rvaser** [comment]
Hi Michel,
somehow `bioparser` was not up do date anymore. Try `git pull origin master` and `git submodule update` from racon root, and recompile afterwards .

Best regards,
Robert

**Comment by MichelMoser** [comment]
works now! 
thank you very much
