### ISSUE TITLE
SIGSEGV in test suite when using bioparser version 3.0.12, spoa version 4.0.6

### ISSUE THREAD

**Issue by tillea** [lbcb-sci/racon#50]
Hi,
in Debian bioparser and spoa were upgraded to the latest versions.  To accomplish this a [patch](https://salsa.debian.org/med-team/racon/-/blob/master/debian/patches/update_bioparser_and_spoa) was applied.  When building racon with this patch and running the test suite in _gdb_ I get:

    Reading symbols from ../obj-x86_64-linux-gnu/bin/racon_test...
    (gdb) run
    Starting program: /build/racon-1.4.13/obj-x86_64-linux-gnu/bin/racon_test
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    Running main() from /build/googletest-YnT0O3/googletest-1.10.0.20201025/googletest/src/gtest_main.cc
    [==========] Running 15 tests from 2 test suites.
    [----------] Global test environment set-up.
    [----------] 5 tests from RaconInitializeTest
    [ RUN      ] RaconInitializeTest.PolisherTypeError
    [Detaching after fork from child process 4055554]
    [       OK ] RaconInitializeTest.PolisherTypeError (4 ms)
    [ RUN      ] RaconInitializeTest.WindowLengthError
    [Detaching after fork from child process 4055557]
    [       OK ] RaconInitializeTest.WindowLengthError (3 ms)
    [ RUN      ] RaconInitializeTest.SequencesPathExtensionError
    [Detaching after fork from child process 4055559]
    [       OK ] RaconInitializeTest.SequencesPathExtensionError (3 ms)
    [ RUN      ] RaconInitializeTest.OverlapsPathExtensionError
    [Detaching after fork from child process 4055560]
    [       OK ] RaconInitializeTest.OverlapsPathExtensionError (6 ms)
    [ RUN      ] RaconInitializeTest.TargetPathExtensionError
    [Detaching after fork from child process 4055561]
    [       OK ] RaconInitializeTest.TargetPathExtensionError (6 ms)
    [----------] 5 tests from RaconInitializeTest (22 ms total)

    [----------] 10 tests from RaconPolishingTest
    [ RUN      ] RaconPolishingTest.ConsensusWithQualities
    [New Thread 0x7ffff71f7700 (LWP 4055562)]
    [New Thread 0x7ffff69f6700 (LWP 4055563)]
    [New Thread 0x7ffff61f5700 (LWP 4055564)]
    [New Thread 0x7ffff59f4700 (LWP 4055565)]
    [racon::Polisher::initialize] loaded target sequences 0.000784 s
    [racon::Polisher::initialize] loaded sequences 0.040465 s
    [racon::Polisher::initialize] loaded overlaps 0.000357 s
    [racon::Polisher::initialize] aligning overlaps [====================] 0.570651 s
    [racon::Polisher::initialize] transformed data into windows 0.002290 s
    [racon::Polisher::polish] generating consensus [====================] 1.046491 s
    ./test/racon_test.cpp:104: Failure
    Expected equality of these values:
      polished_sequences.size()
        Which is: 1
      2

    Thread 1 "racon_test" received signal SIGSEGV, Segmentation fault.
    0x00005555555890b1 in calculateEditDistance (query="", target=<error reading variable: Cannot access memory at address 0x28>) at /usr/include/c++/10/bits/basic_string.h:186
    186           _M_data() const

Do you have any idea how to fix this SIGSEGV?

Kind regards, Andreas.

**Comment by mr-c** [comment]
@rvaser volunteered to look into this at https://github.com/lbcb-sci/racon/pull/48#issuecomment-757629645

Assistance from others is welcome as well!

**Comment by rvaser** [comment]
Hi @tillea, @mr-c,
can you please try the latest commit and see if everything works now? I will create new releases for biopaser, spoa, thread_pool and racon shortly. Sorry for the delay.

Best regards,
Robert

**Comment by mr-c** [comment]
@rvaser The latest racon commit works, thanks! 

Yes, tagged releases for biopaser, spoa, thread_pool and racon  will be appreciated

**Comment by rvaser** [comment]
I have released new versions for all tools. Let me know if you need anything else.

**Comment by mr-c** [comment]
@rvaser Thanks! I've updated & upload the Debian source packages for spoa, thread_pool, racon, and rampler (we had already packaged the updated bioparser). This issue can be closed.
