### ISSUE TITLE
docker support

### ISSUE THREAD

**Issue by huangnengCSU** [lbcb-sci/racon#51]
Hi，
    Can you provide the docker image for Racon?

Best
Neng Huang

**Comment by rvaser** [comment]
Hello,
there is already a Conda package. If that is not sufficient, I'll add it to a to-do list.

Best regards,
Robert

**Comment by rpetit3** [comment]
@huangnengCSU

Please checkout https://quay.io/repository/biocontainers/racon?tab=tags
