### ISSUE TITLE
Can racon only fill gaps?

### ISSUE THREAD

**Issue by zmz1988** [lbcb-sci/racon#56]
Hi, I have a question about whether I can use racon for gap closing.

I have a scaffold that are scaffolded by polished contigs along the reference. The scaffold still has around 3000 Ns in it. I would like to align my scaffold against the Nanopore reads again, to see whether some contigs can be connected by reads. Can I use racon for another run of polishing but only for the gap region?

Also, I have question about racon polishing, when there are Ns in the contigs. Will Ns be simply trimmed off Ns because of low coverage? Or will Ns be replaced by the consensus of aligned reads in that region?

Thanks!

**Comment by rvaser** [comment]
Hello,
Racon was **not** designed for gap filling, but could polish over gaps if they are not too long (used mapper can place longer reads over them) and not located at the ends of the windows (they could get trimmed away if nothings maps onto them). Unfortunately, polishing a specific part of a target sequence is not implemented yet (I think @isovic implemented that in https://github.com/lbcb-sci/racon/tree/bed, but we have not yet joined the branches).

Best regards,
Robert

P.S. Sorry for the late reply.

**Comment by zmz1988** [comment]
Thanks Robert! Sorry for thanking you late. I still have a question about what you mentioned "could polish over gaps if they are not too long (used mapper can place longer reads over them)". I just like to confirm whether racon can pick up the whole length of the missing sequence from the longer reads overlapped? I mean, for example, 10 Ns are artificially added to connect two contigs in my scaffold. When mapping reads back to the scaffolds, there are longer reads overlapping the conjunction sites between the two contigs. However, there are 1000 bases in the reads were found between the contigs, which is 10 times longer than the Ns in the scaffold. So in this case, will racon pick up the 1000 bases to fill the Ns?

I ask this because I think, if racon is reliable in filling small regions with Ns (if there are longer reads covering), then I could use it to do one run polishing after scaffolding. I already tried, and see a lot of improvements in decreasing Ns in my scaffolds. But I would like to confirm whether it is proper/reliable to do so.

Thanks a lot in advance!

**Comment by rvaser** [comment]
Everything depends on the overlaps/alignments. If both the gap and the insertion fall into a single window, it should work I suppose (see below).
```
Ref:  (W_b) xxxxx ... (10)N ... xxxxx (W_e)
Read: (W_b) xxxxx ...  (?)I ... xxxxx (W_e)
```
```
Ref:  (W_b) xxxxx ... (10)N ... xxxxx----------- (W_e)
Read: (W_b) xxxxx ... IIIIIIIIIIIIIIIIIIIIIxxxxx (W_e)
```
If the gap is at a window end, reads might align differently to the two windows that share the gap and you could get a weird consensus. Maybe running racon again could solve the mess, not sure. Overall, gap filling has never been tested :)
```
Ref:   ... NNN (W_e) || (W_b) NN ...
Read1: ... ab- (W_e) || (W_b) -c ...
Read2: ... a-- (W_e) || (W_b) bc ...
Read3: ... abc (W_e) || (W_b) -- ...
```

Can you verify how the accuracy of your polished scaffolds changes? Quast/BUSCO maybe?

**Comment by zmz1988** [comment]
Thanks a lot, Robert! 

Here is some polishing results:
```
                               scaffold                      scaffold_racon1round
base-level QV                  55.5                          53.1
N's                            10300                         5575
```

The BUSCO results are quite similar, 98% single complete for both scaffolds.

Considering relatively lower QV in the scaffolds after polishing, I guess I will just use the one without polishing?

Thanks a lot for your helpful answers!

**Comment by rvaser** [comment]
I think you should stick with the scaffolds without polishing. Sorry for my late reply!

**Comment by zmz1988** [comment]
Thanks a lot!!
