### ISSUE TITLE
How to obtain Contigs from cDNA Nanopore Sequencing

### ISSUE THREAD

**Issue by jkbenotmane** [lbcb-sci/racon#57]
Hi,

I am working with highly diverse Immune cell transcripts obtained from cDNA Nanopore Sequencing.

Would you have any advice on how to obtain the contigs needed for Racon from cdna Sequencing Data?

**Comment by rvaser** [comment]
Hi Jasim,
unfortunately, I think that Racon won't be able to properly handle transcript data due to alternative splicing. You can try out https://github.com/ksahlin/isONcorrect.

Best regards,
Robert

**Comment by jkbenotmane** [comment]
Okay understandable. 
Thank you ! :)
