### ISSUE TITLE
Incompatible with latest spoa release

### ISSUE THREAD

**Issue by tillea** [lbcb-sci/racon#6]
Hi,
when trying to build the latest release of racon (1.4.6) against the latest release of the spoa library (3.0.1) I get:

    /build/racon-1.4.6/src/window.cpp:90:43: error: 'using element_type = class spoa::AlignmentEngine' {aka 'class spoa::AlignmentEngine'} has no member named                           'align_sequence_with_graph'
       90 |             alignment = alignment_engine->align_sequence_with_graph(
          |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
    /build/racon-1.4.6/src/window.cpp:96:43: error: 'using element_type = class spoa::AlignmentEngine' {aka 'class spoa::AlignmentEngine'} has no member named                           'align_sequence_with_graph' 
       96 |             alignment = alignment_engine->align_sequence_with_graph(
          |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
    make[3]: *** [CMakeFiles/racon.dir/build.make:118: CMakeFiles/racon.dir/src/window.cpp.o] Error 1

I guess I might need some code that is not (yet) tagged as release.  Any hint how to fix this?
Kind regards, Andreas.

**Comment by rvaser** [comment]
Racon uses spoa `v1.1.3`. Is it necessary to upgrade to latest version?

**Comment by tillea** [comment]
On Wed, Sep 18, 2019 at 01:36:20AM -0700, Robert Vaser wrote:
> Racon uses spoa `v1.1.3`. Is it necessary to upgrade to latest version?
Hmmm, I just upgraded spoa independently for other reasons in Debian.  It would cause quite some work and some ugly version overriding which I'd love to avoid.  Do you see any chance to upgrade to latest spoa without much effort?
Kind regards, Andreas.

**Comment by rvaser** [comment]
I released a new racon version `v1.4.7` which should have everything up to date.

Best regards,
Robert

**Comment by tillea** [comment]
Hi Robert,
On Wed, Sep 18, 2019 at 02:12:25AM -0700, Robert Vaser wrote:
> I released a new racon version `v1.4.7` which should have everything up to date.
Thanks a lot for your fast response.  I've thought now it would be ease to update racon on Debian but unfortunately there is an issue with the new dependency liblogger.  While I have created a package from it oour ftpmasters have two arguments against it: 1. Its a really generic name for quite some special thing.  2. Its just a single file wrapped into an extra package.  The recommendation was that I should simply put logger.cpp (back) into racon source code.
What do you think about this?
Kind regards, Andreas.

**Comment by rvaser** [comment]
I'll try and sort this out as soon as possible.

**Comment by tillea** [comment]
On Fri, Sep 20, 2019 at 02:49:26AM -0700, Robert Vaser wrote:
> I'll try and sort this out as soon as possible.
Did you found any solution?  Kind regards, Andreas.

**Comment by rvaser** [comment]
Hi Andreas, yes I have a plan how to deal with it but I am not available for a week or more. Will let you know.

**Comment by tillea** [comment]
On Tue, Oct 08, 2019 at 03:51:47AM -0700, Robert Vaser wrote:
> Hi Andreas, yes I have a plan how to deal with it but I am not available for a week or more. Will let you know.
Thanks a lot.  Just take your time until end of October since I'll be not available until then. ;-)

**Comment by tillea** [comment]
Any news?  I admit I'd be happy to have some solution without liblogger to enable build with latest spoa.  Thanks a lot, Andreas.

**Comment by rvaser** [comment]
Hi Andreas,
I'll do my best and finish this by the end of the week.

Best regards,
Robert

**Comment by rvaser** [comment]
@tillea, I followed your advise to just include the logger source into Racon. I do not have the time for a more elegant solution at this point. The new version (`1.4.10`) has been published.

**Comment by mr-c** [comment]
I can confirm the latest version of racon `1.4.10` is compatible with the version of spoa in Debian's development repository. Thank you @rvaser !
