### ISSUE TITLE
Polishing polished assembly -> invalid file format

### ISSUE THREAD

**Issue by an22an** [lbcb-sci/racon#72]
Hello,
i am using racon via docker and it's working fine so far when polishing an assembly for the first time. 
I polished  a canu created assembly with racon and ont reads and then i wanted to polish it again but i get the error:

racon -t 5  'KlebselliaPneumonia/Raw/OxfNanoPore/SRR8494939_1.fastq' 'KP_R_LR/KP_LR_R_ONT.fasta_rl_map.paf' 'KP_R_LR/KP_LR_R_ONT.fasta' > 'KP_LR_R_testR_LR.fasta.fastq'

terminate called after throwing an instance of 'std::invalid_argument'
  what():  [bioparser::FastaParser] error: invalid file format 

This is how head and tail looks like. I appreciate any help and many thanks in advance!

 head -n 1 KP_LR_R_ONT.fasta.fastq
>C9_5259916 LN:i:5289977 RC:i:70022 XC:f:1.000000

tail -n 4 KP_LR_Medaka_RaconR_ONT.fasta.fastq
>C2_0004207 LN:i:4169 RC:i:162 XC:f:1.000000
TTTCTACGCATGCTCCTGCCGCTCGCCGCAGCCGAACGGCAGGAGCGTAGCGACTGAGTGAGCGAGGAAGCGGAAAAGAGAACATCCTTACACTGAGCACTGACGCTCTGAGGCCTCTTATGACGAAACAACAGAAAACAGCGCTGAACATGGCTAAATTCATCCAGAATCAGTCTCTGCTCCTGCTGGAGAAGCTTAACGAGCTTGATCTTGATGCTGAGGCTGACCTTTGTGAGAAACTCCACGATGATGCGGAGCATCTTTTCCGTACACTGTCCTCGAGACTGGATGCATTACAGGATGGTAACTGATGGCCAGAGTGTCTATTAGTGAGGCTGCCCGACTGACGGGTAAGAGTAGAACAACACTGCACAGGTTAATTAAAGCAGGTGACCTGTCCACCTGTAGCGGTGAACGCAATGCAAAATGGTAGATACTTCAGAGCTTTTACGTGTCTTTGGTCCCTTTGAGCAACCGAAGGGTGAACACCATTCTGGACAGGTCTCTGAACAGCGTGATACAGCCTCTGCTGACCAGAGTGAACAGGTGATTCGTCATCTGAAACAGGAGATTGAACACCTGAACACCTTACTTTTGTCCAAGGATTCGCACATTGACAGCCTGAAACAGGCCATGCTCCTTCTTGAAAATCACCGGGCAAAATTAACTGAATCCCCGGCGCCATGGTGGAAATTCTGGAAAAATCCTGATCCTGCCATGCTTGAGTTTTCCTCTCCGGCCATCCCGGGGAGTTCCTGAACCTTCCCAAAATCGCCAGATCTCTGAACGCTCCTCACCACTAAAAAATACCCACACACTACGCAAAATTAAAATTTTGCGGATTTGTATTTAATATCAGTTAGTTACTTTCCTGAAATTTCGTTTTTAAATTTTATTTACATAGATCCGACTCTATGACGACTCGTCATAGAGTCCCCGGCGAGTCGTCATGGAGTCGGTAACGACTCAGGACTATAAAACAATGAGTTAATAACGACCCGACTCTAGACCCGACTCCCCGTTTGGTTGTTTTTAGACGTGGCGACTCTGGGTACGACTCTAGTGAAGAGTCGCCGGTGAATCGTGTGGTGAGTCGTCCGGCGACTTGCCACACGCCATTGCCGGCTGTCGATGGGCCCGATTCCTGAAGGTGTTGAAAACGGTTTTCCGGCTGTGCCGGCAACGCCTCACGGCCACGCAATAAATTGCGTCCCCATTCACCGTTTTCAGTCGGGTTTGGTGCGGGTTTCGAGTCGTCTGGCCTAAATTCAGGCTGAAATCTGCCACCAGTCAGTCTGGTGCATAACGATTCATGCCCGTAAAACGCCCCGGAGCGATTTTGAGGCGTTTTCAGGGGGGGGTAAGACGTAGGATTTAATGGGTTACGCCCCAGAATCGTTCTGAGGCCGTTTTAGCGGTGCGTGTAATGACGCGTTATGGTAAATCCAGTAGTTTTTGCTCATTCAGGAGTGGTTTTAAATCATCATGTATGAATATCTTGTAATGGTAGGTATAGTTAGCATGGATATTGCTAAGGATAAAAGCATAACATACTTAGTGGGTGATGCGAATGGAAATAGAGTTTGAAAATATCGGCTTTATAAAAAGCGGGAAAATAAAACCAATAACATTACTGTTATTTTTGGGCCAAATAATGTGGGTAAAACATACCTAAGTTATAGCACATACGCTGCTATTAGTAGGTACAATGACATATTTAGAGAGAAAATAAAAATACCAAAATCAGTATCTAGCAACCTTTGGTTTTAAACGGAACTGCCGGTACGACATCACAAACGTTTTTACTGATTCTCTTGTTAAATCAGTTAATGAAGAGGTTTCATCAAGCTTACCTGCATTCTTCAAAGATAGTTCAGGTATGTTTTCTAAATCAAAAATTAGTGTGATTGACTCTTATATTAAAGATAGAGTTGTTAATTCTGAAGTTAATGTAAATATTTCTGTCAGTGAAAATATAATATTAAATATACAAAAAAAAAAAAAAAAAACAATACATGTATTGATTTTACAGTCACCTCATCCAAAAGAATAATGAGTCAGGGAGTCCTGTCATTGATCTGAAGGAAAAAGACGCTTCAAATTATTTAAATATTTTATTTAATTTCTTTTTTTCCTTAATGAGGTTTTAGACTCTGCAGCTAATAACGCATTTATAATAACATCTGAGCGTACTGGAATATCCTTGTTTCAAAAGGAGATTGATGGTAATCGTAGTAATATTGTTGATTCTTACATGTGGAGTAAGTTGTCTACGAGGAAGTTACTGTCTTTTGATGACATTATGAGCCAGAAAGTTGCTAAATTCTCGGAGCCAATTAATCACAATATAAATATAATAAGAGACTTTGCTGATCTGAAAAAATGAAGCATATAATGACGGCAAATGGTGTTAGAAGGGCATCTAAGGAGCGAGCTGATGTTATAAAAACACTAGAGTCACTTACTGGTGGCAGATACTCAACATCTGACGGTGAGGCTATTTTTACAGTTTCTTGCAGTGATGGAGATAAAGTGTCAATGCCACTTTCTCTCTCATCAGCATCTAACAAAGCACTATTTCTATTAGATATATATGTAAGATACTACATGTCTAATAACTCTTACTTGATAATTGATGAGCCAGAGCTGAATCTGCATCCACATAATCAAATTAAAATGGCAGAGTTGCTTGTAAGACTTTCAAATTGCGGAGTTAAAATTATAATCACAACGCATAGTGATTATATCGTTAAAGAGATTAATAATAGAATAATGGCTTCGCAGCTGAAAGATAAATCACGATTAACTGAACTTGGATACAAAGAAGCAGATTTGATTTTTTCGTCAGAGGTTAATGGTTTTACTATCGGTAATGATGGTGCCATCTCTGAGGTTGAAGGGAATAGGTATGGGGTGAATGCTTTTTTTTTGATAATGTTATTAATGATATAGAAAACAAGGCTGATCTCTTGTATACATATTTAGAAGAGGGCTCTAATATGCTGGAGAGGTTTATTGATGTTTTAAATAAAGATGTTTTGTTTGATTTGTCGGCAACTCCATCTCCTGACTCTTCGGTGTTAGTTGTTCGTGAAGATGGTGAGCTTAGTGAAATAAAAGAGTTAACTATAAAAGAAATACCTGATGATTCGATTGCTTTCACTTTGGATTTTTCAAGCAAGAAAAACTCTAAAGAAAATGGCGCTTTATTTTCTCAATTGTCGCCATACTTTGACAAGTCTAATGGCGATGGGGTGAATAAATCTTGTGATCTTGTATTGATTACAAGAGATGGCGATAAGTTCACTGTTCTTATTTTTGACCAAAAGTCAAAAAAACCTGATATAGAATCATCATTTTGCAGTTGGAAAACTCAAGAGTTTTTGTTTCCTATGTAATTAATATTATTTCTTTAATTTATAAAGACAATATTGATGAGGGGAAGATTATTTTTAAACGAGTTATTGGGACTACAAGGGTTGTAAAAACTGGAGTTAATGCTGCTAATCATGAGCAGGAACGATCGAGAAGAGAGAAGCTTCGTGCTCTTGGCATGAATGAAGTCTCGATAAAGCGTACGGCATCAATAGAAAAGGGATGGTTGGACTATCGAGGAATCGTTTCCTTTTAGTCTACTTCCAGTAGTCTCAAGTGCTTGTGTTGAGAGAGGAAGAACGGTATCTTTCAACATATAAAGAAAAACCACCGCTACCAACGGTGGTTTTCTTAAGGTTTATGGAGCTACCAACTCATTAAACCTAGGTAGCTGGCTTGGAGGAGCACAGTCACCAAAACTTGTTCTTTCAGTTTAGCCTTAACAGGCGTCTAACTTCAAGACTATCTCCTCTAAATCAGTTACCAGTGGCTGCTGCCAGTGGCGCTTTTGCATGTCTTACCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGACTGAACGGGGGTTCGTGCATACAGTCCAGCTTGGAGCGAACTGCCTTCCCGGAACCGAGTGTCAGGCGTGGAATGAGAAACCGCGGCCATAACAGCGGAATGACACCGGTAAACCGAATGGCAGGAACAGGAGAGCGCACGAGGGAGCCACCTATCAGAAATGATAGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCACTGATTTGAGCGTCTTTCTGTGATG
>C8_0003392 LN:i:3091 RC:i:376 XC:f:1.000000
CCAGACTATCAGTAACTTATGACGACTTGACTCTAGAGTTGAGTCGTTCATTTGGTGTTTTTGACCTTGGTGACTCTAGAGTCAAGTCACGAGTCGAATCGCCGGTGAATCGTGTGCTAAGTCGTCCGGTGACTTGCCATCACGTCATTGCCGGCTGTCGCTGAACTGGATTCTTGAACGTGCTGAAAACGGGTTTTCCGGCTGCGCCGGCAACGCCTCACGGCCACGCAATAAATTGCGTCCCCGTTCACCGTTTTCGGATCAGAAAAACGCCGGAAACAGGACTTACCCCGGCTGAATGGCATGAATTCCCGCGCTATGCACTTGCATGCATACTCATGTATGCCGTAAAACAGCCCCTGCGCGTTTCTGGCAGGTTTTCGGGTGGTTTGTTGCCTGTTTTGCCGGTTTCCCGTCAGAAACGCCCTGAAGCCGTTTTAGCGGTGCACGTAATAGGGCTTTATGTTAAATTAAGACTGGTTTGATGTTTAAACTTATAGTGATCTTTTTAGTGTGTTACTCCAATTCGAATAGTACACCCCTTTCCTGCTGCAGCAATTCGAACTAGCTCATCAACAGTCTTGGACTCAAGATCAAACAGAACTAACTTTGCTTTATTGGGGTTATCGAGTTACCTGCGGCTGCGGCAATCCGCACGAGCTGATCCACTGTTTTTGTGGATGCACTTAAACGTAAACCACCTCCTGCTGCAGCAATCCGAACTAATTGATCTACTGTTTTCAAGTCTCTTTCTCCTTGTTCTTTCTGAAGTTCTTCATACTGGTCTTTGTTGTTACTAATTGATATTAATAGCTTTTCTATCAAAGGTTCAAAGCTGTAAAGATTGCTCAAGCCTTTGTCATTGACTGATTTTGCGCGGATTTTCTCTTCAAGACCCCTTTAGATATTAATTTGTTTATGGTTCGCTGCACGGTTCTTGGGTGTTGGTTGATCCTACCTGCTAGTGTAGAAATGCTTGGGGTATTTATTTGTTTAAGTAGTTACCTTTTAGGGTGGCATTGGTGCCACCCTTCAAACTGAACTCAAAGACTATACAATACAAATATTGTTTACACATTGTTTATCCATCTGCTTTGGAGGTATTATGACTACGGCTATTGGTAAATGGGGTAATGGCGCTGCTTTGCGTATCCCGCAGCCGTTCATGAAGCAGCTTGGGCTTAGTATCGGTGATGTTGTTAATTTCCGCGTCACTGAAAGGATTTTAGTAATTACTAAAGCTGGCCCGACGCTTGAAGAACTGCTCGGACAGTGCACTGCAGAAAATCGCCATCACGAGTATCTATGTGACTCTCAAGGTAAGGAGATGCTGTGACGACATATTGTCCAGCCAGAGGCGATGTCATTCTTTTAGATTTTAACCCTCAATCAGGGCATGAGCAGGCAGGGGAAAAGGCCTGCTCTTGTCGTTTCTGATGATTTGTTTAACCAAGTCACTGGGTTTGCTGTTGTTTGCCCCATAACTAATCAGATAAAAGGGTACCCTTTTGAAGTTCCTGTTGATGGGACTACTAAAACAACAGGGGTTATCTTGGCTGATCAAGTGAAGTCTTTAGACTGGAAGGCCAGAGCGGCACGTACTGTTGATAGCGTTTCCGGCGAGACAGTAACTACAGTTGTTGATATGGTTTCAAAATTATAAAGCATAAAAAGACCGGCATAAGCCGGTCTTTTCAGGCCGAAAATGTTACCAGCATTTTCGGCCTTCGGTGACTGCTCTAAAGGGGAACAGTAACCAATATTGTTTATCAAGTGTAACTGCTTACTGTTACAGCAATCAAGATTTTCTTTCCCCGTAGAGCGACCGATGGCTACTGCCAATGGCGCTTTGGCGTGCTTGTTCGGGTTGGACTCAAGTTGATAGTTACCGAATTAGCGCAGTAGTCGGACTGAACGGGGGTTCGTGCATACAGTCCAGCTTGGAGCGAACTGCCTAACCGGAACTGAGTGTCAGGCGTGGAATGAGATAAACGCGGCCATAACAGCGGAATGACACCGGTAAACCGAAAGGCGGGAACAGGAGAGCGCACGAGGGAGCCATCAGGGGAAACGCCCGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCACTGATTTGAGCGTCAAATTTTGTGATGCTTGTTGGGGGGGCGGAGCCTATGGAAAAACGGCCGTTGTGCGGCCTTGTCTCTCTTCGTGCTGTCTGTCCTATGCCGTTATGTGTGCGTTGCGACCGCTCGCCGCAGCCGAACGGCAGGAGCGTAGCGACTGAGTGAGCGAGGAAGCGGAAAAGAGACTGGTTTTACACTGAGCACTGACGCTCTGAGGCTTCTTATGACGAAACAACAGAAAACAGCGCTGAACATGGCTAAATTCATCCAGCATCAGTCTCTGCTCCTGCTGGAGAAGCTTAACGAGCTTGATCTTGATGCTGAGGCCGACCTTTGTGAGAAACTCCATGATGATGCGGAGCATCTTTTCCGTACACTGTCCTCGAGACTGGATGCATTACAGGATGGTAACTGATGGCCAGAGTGTCTATTAGTGAGGCAGCCCGATTGACGGGTAAGAGTAGAACAACACTGCACAGGTTAATTAAAAGGTGACCTGTCCACCTGTAGCGGTGAACGTAATGCAAAATGGTAGATACGTCAGAGCTTTTGCGTGTCTTTGGTTCCTTTGAGCAACCTAAGGGTGAACATCTTTCTGGACAGGTCTCTGAACAGCGTGATACAGCTTGCTGACCAGAATGAACAGGTTATTCGTCATCTGAAACAGGAAATTGAACACCTGAACACCTTACTTTTGTCCAAGGATTCGCACATTGACAGCCTGAAACAGGCCATGCTCCTTCTTGAAAATCACCGGGCAAAATTAACTGAATCCCCGGCGCCATGGTGGAAATTCTGGAAAAGTCCTGACACCGTCATGCTTCAGTTTTCCTCTCCGGCCATTCCGGGGAGTTCCTGAACCTTCCAAAAATCGTCAGATCTCTGAACGCACCTCACCACTTAAAATACCCACACCACGCAAAATTAAAATTTTGCAGATAACTCATTAATATCAGTTTGTTAGGTGTTATTAAATTACGA

**Comment by mmnascimento** [comment]
I'm having the same issue, how did you solve it?
