### ISSUE TITLE
Reads extending over the edge of the contig

### ISSUE THREAD

**Issue by diego-rt** [lbcb-sci/racon#75]
Hello,

I was wondering how does racon handle reads that extend over the edge of the contig? Will it extend the contig? Or do you need to have N's at the ends in order to extend them? 

Thanks a lot!

Diego

**Comment by rvaser** [comment]
Hi Diego,
I would say it depends on the alignment. If it is a soft clip, the contig won't be extended. If it is somehow an insertion followed by a match/mismatch at the end, it might get extended but depends on how many reads agree on it.

Best regards,
Robert
