### ISSUE TITLE
Correcting fused regions

### ISSUE THREAD

**Issue by ghost** [lbcb-sci/racon#9]
Hello,

I have a ONT genome assembly with Ra, where I have good reasons to suspect some multi-copy regions have been fused at the assembly step. Is Racon able to "correct" that, i.e. expand those regions? 
If yes, should I used the "correct fragments instead of polishing" parameter? It is not really clear to me what this does. 

Thanks a lot

**Comment by rvaser** [comment]
Hello,
Racon only polishes what is given and does not deal with SNPs nor variations, if that is what you are asking :)

Best regards,
Robert

**Comment by ghost** [comment]
it does

thank you!
